-- Наполнение таблицы master_listings демо-мастерами
-- Запусти этот файл в SQL Editor после SETUP_NEW_PROJECT.sql и SEED_SERVICES.sql

WITH master_seed (
  full_name,
  phone,
  avatar_url,
  bio,
  service_categories,
  working_districts,
  experience_years,
  average_rating,
  total_reviews,
  price_min,
  price_max,
  latitude,
  longitude,
  ranking_score,
  completed_orders,
  cancelled_orders,
  response_time_avg,
  repeat_clients,
  complaints,
  quality_flag,
  is_top_master,
  is_active
) AS (
  VALUES
    (
      'Фирдавс Каримов',
      '+992 900 11 22 33',
      '',
      'Электрик с большим опытом. Быстрый выезд по Душанбе, аккуратный монтаж и диагностика.',
      ARRAY['Электрика','Умный дом'],
      ARRAY['Сино','Фирдавси'],
      9,
      4.9,
      128,
      60,
      250,
      38.5732,
      68.7861,
      96.4,
      312,
      6,
      18,
      47,
      1,
      'good',
      true,
      true
    ),
    (
      'Рустам Саидов',
      '+992 901 22 33 44',
      '',
      'Сантехник по квартирам и домам. Установка бойлеров, устранение протечек, замена труб.',
      ARRAY['Сантехника','Отопление'],
      ARRAY['Шохмансур','Сино'],
      11,
      4.8,
      154,
      80,
      320,
      38.5564,
      68.7519,
      94.8,
      340,
      9,
      22,
      58,
      2,
      'good',
      true,
      true
    ),
    (
      'Далер Назаров',
      '+992 902 33 44 55',
      '',
      'Мастер по отделке: шпаклевка, штукатурка, укладка плитки, откосы и финишные работы.',
      ARRAY['Отделка','Малярные работы','Полы и ламинат'],
      ARRAY['Фирдавси','Сино','Исмоили Сомони'],
      8,
      4.7,
      96,
      70,
      280,
      38.5482,
      68.7794,
      90.5,
      221,
      7,
      30,
      36,
      1,
      'good',
      false,
      true
    ),
    (
      'Сомон Юсупов',
      '+992 903 44 55 66',
      '',
      'Сборка мебели, установка дверей и замков. Работаю быстро и аккуратно.',
      ARRAY['Мебель и двери','Другие услуги'],
      ARRAY['Исмоили Сомони','Шохмансур'],
      7,
      4.8,
      88,
      50,
      220,
      38.5651,
      68.8012,
      89.7,
      205,
      5,
      25,
      29,
      0,
      'good',
      false,
      true
    ),
    (
      'Бахром Ашуров',
      '+992 904 55 66 77',
      '',
      'Специалист по видеонаблюдению и домофонам. Настройка удаленного доступа и монтаж CCTV.',
      ARRAY['Видеонаблюдение','Умный дом','Электрика'],
      ARRAY['Сино','Пригород'],
      10,
      4.9,
      117,
      100,
      400,
      38.5920,
      68.8126,
      95.6,
      276,
      4,
      16,
      41,
      0,
      'good',
      true,
      true
    ),
    (
      'Фаррух Исмоилов',
      '+992 905 66 77 88',
      '',
      'Установка и обслуживание кондиционеров. Чистка, заправка, ремонт, демонтаж.',
      ARRAY['Кондиционеры','Отопление'],
      ARRAY['Фирдавси','Шохмансур'],
      12,
      4.8,
      142,
      120,
      450,
      38.5408,
      68.7688,
      93.9,
      298,
      8,
      24,
      53,
      1,
      'good',
      true,
      true
    ),
    (
      'Абдулло Мирзоев',
      '+992 906 77 88 99',
      '',
      'Клининговый мастер: генеральная уборка, окна, уборка после ремонта и химчистка мебели.',
      ARRAY['Уборка'],
      ARRAY['Сино','Фирдавси','Шохмансур'],
      6,
      4.6,
      75,
      15,
      120,
      38.5533,
      68.7441,
      84.2,
      168,
      6,
      35,
      20,
      1,
      'good',
      false,
      true
    ),
    (
      'Шамсиддин Олимов',
      '+992 907 88 99 00',
      '',
      'Маляр и мастер по покраске стен, потолков и фасадов. Делаю ровно и чисто.',
      ARRAY['Малярные работы','Отделка'],
      ARRAY['Исмоили Сомони','Фирдавси'],
      9,
      4.7,
      83,
      40,
      180,
      38.5719,
      68.7586,
      87.8,
      194,
      7,
      28,
      24,
      1,
      'good',
      false,
      true
    ),
    (
      'Джамшед Рахматуллоев',
      '+992 908 99 00 11',
      '',
      'Специалист по полам и ламинату. Стяжка, наливной пол, линолеум, паркет.',
      ARRAY['Полы и ламинат','Отделка'],
      ARRAY['Шохмансур','Пригород'],
      8,
      4.7,
      69,
      45,
      210,
      38.5340,
      68.7935,
      86.9,
      177,
      5,
      26,
      22,
      0,
      'good',
      false,
      true
    ),
    (
      'Сироджиддин Хакимов',
      '+992 909 10 20 30',
      '',
      'Срочный мастер 24/7: аварийная сантехника, электрика, мелкий ремонт и выезд ночью.',
      ARRAY['Другие услуги','Электрика','Сантехника'],
      ARRAY['Сино','Фирдавси','Шохмансур','Исмоили Сомони'],
      13,
      4.9,
      165,
      100,
      500,
      38.5602,
      68.7725,
      97.1,
      364,
      10,
      12,
      73,
      2,
      'good',
      true,
      true
    ),
    (
      'Камол Набиев',
      '+992 911 21 31 41',
      '',
      'Мастер по бытовой технике. Подключение стиральных машин, плит, вытяжек и холодильников.',
      ARRAY['Другие услуги','Сантехника','Электрика'],
      ARRAY['Исмоили Сомони','Сино'],
      7,
      4.6,
      58,
      70,
      260,
      38.5465,
      68.7842,
      82.3,
      149,
      8,
      29,
      18,
      1,
      'good',
      false,
      true
    ),
    (
      'Зафар Бобоев',
      '+992 912 32 42 52',
      '',
      'Универсальный мастер по дому: карнизы, зеркала, ТВ, мелкий монтаж и доработки.',
      ARRAY['Другие услуги','Мебель и двери'],
      ARRAY['Фирдавси','Исмоили Сомони'],
      5,
      4.5,
      44,
      40,
      150,
      38.5791,
      68.7664,
      78.6,
      122,
      6,
      32,
      11,
      0,
      'good',
      false,
      true
    )
)
INSERT INTO public.master_listings (
  full_name,
  phone,
  avatar_url,
  bio,
  service_categories,
  working_districts,
  experience_years,
  average_rating,
  total_reviews,
  price_min,
  price_max,
  latitude,
  longitude,
  ranking_score,
  completed_orders,
  cancelled_orders,
  response_time_avg,
  repeat_clients,
  complaints,
  quality_flag,
  is_top_master,
  is_active
)
SELECT
  ms.full_name,
  ms.phone,
  ms.avatar_url,
  ms.bio,
  ms.service_categories,
  ms.working_districts,
  ms.experience_years,
  ms.average_rating,
  ms.total_reviews,
  ms.price_min,
  ms.price_max,
  ms.latitude,
  ms.longitude,
  ms.ranking_score,
  ms.completed_orders,
  ms.cancelled_orders,
  ms.response_time_avg,
  ms.repeat_clients,
  ms.complaints,
  ms.quality_flag,
  ms.is_top_master,
  ms.is_active
FROM master_seed ms
WHERE NOT EXISTS (
  SELECT 1
  FROM public.master_listings existing
  WHERE existing.full_name = ms.full_name
    AND existing.phone = ms.phone
);
